export { default as ErrorPage } from './ErrorPage/ErrorPage'
export { default as Home } from './Home/Home'
export { default as Game } from './Game/Game'
export { default as Profile } from './Profile/Profile'
export { default as Forum} from './Forum/Forum'
export { default as ForumTopic} from './ForumTopic/ForumTopic'
